local map = vim.keymap.set

map("n", "<C-p>", "<cmd>Telescope find_files<cr>", { desc = "IntelliJ: Go to File" })
map("n", "<C-S-f>", "<cmd>Telescope live_grep<cr>", { desc = "IntelliJ: Find in Files" })
map("n", "<C-b>", "<cmd>NvimTreeToggle<cr>", { desc = "IntelliJ: Project Tree" })
map("n", "<C-S-b>", "<cmd>lua require('dap').toggle_breakpoint()<cr>", { desc = "Toggle Breakpoint" })
map("n", "<F5>", "<cmd>lua require('dap').continue()<cr>", { desc = "Debug Continue" })
map("n", "<F8>", "<cmd>lua require('dap').step_over()<cr>", { desc = "Debug Step Over" })
map("n", "<F7>", "<cmd>lua require('dap').step_into()<cr>", { desc = "Debug Step Into" })
map("n", "<S-F8>", "<cmd>lua require('dap').step_out()<cr>", { desc = "Debug Step Out" })
map("n", "<A-CR>", "<cmd>lua vim.lsp.buf.code_action()<cr>", { desc = "IntelliJ: Show Intention Actions" })
map("n", "<C-Space>", "<cmd>lua vim.lsp.buf.completion()<cr>", { desc = "Trigger Completion" })
map("n", "<A-b>", "<cmd>lua vim.lsp.buf.definition()<cr>", { desc = "IntelliJ: Go to Declaration" })
map("n", "<C-A-b>", "<cmd>lua vim.lsp.buf.implementation()<cr>", { desc = "IntelliJ: Go to Implementation" })
map("n", "<leader>e", "<cmd>Telescope diagnostics<cr>", { desc = "Diagnostics" })
map("n", "<leader>db", "<cmd>DBUIToggle<cr>", { desc = "Database UI" })
map("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find Files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Live Grep" })
map("n", "<leader>/", "gcc", { desc = "Comment Line", remap = true })
map("v", "<leader>/", "gc", { desc = "Comment Selection", remap = true })
